<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
		<UseWPF>true</UseWPF>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<IsPackable>false</IsPackable>
		<IsTestProject>true</IsTestProject>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.9.0" />
		<PackageReference Include="xunit" Version="2.9.2" />
		<PackageReference Include="xunit.runner.visualstudio" Version="3.1.5" />
	</ItemGroup>

	<ItemGroup>
		<AssemblyMetadata Include="Ymm4Directory" Value="$(YMM4DirPath)" />
	</ItemGroup>

	<ItemGroup>
		<Reference Include="YukkuriMovieMaker.Plugin">
			<HintPath>$(YMM4DirPath)YukkuriMovieMaker.Plugin.dll</HintPath>
			<Private>false</Private>
		</Reference>
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Telemetry\Telemetry.csproj" />
	</ItemGroup>

</Project>
